// Importers/Callers: AppStore, context, seed initializers, WhatsApp Hub, Pricing components.
// Affected API: SUBSCRIPTION_PLANS, DEFAULT_WHATSAPP_TEMPLATES, mock data for local fallback.
// Data Schemas: SubscriptionPlan, WhatsAppTemplate from src/lib/types.ts.
// User's Verbatim Instruction: "c:\AI\Revia_Final_All_Three_Business_Updates_Claude_Code_Prompt.docx now this make todo and complete updaate"

import {
  Business,
  Customer,
  Visit,
  Opportunity,
  WhatsAppTemplate,
  WhatsAppLog,
  SubscriptionPlan,
} from "./types";

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: "starter",
    name: "Starter Plan",
    price_monthly_inr: 499,
    description: "Ideal for small counters & single-location shops beginning customer retention.",
    max_customers: 300,
    features: [
      "Up to 300 active customer records",
      "5-second fast mobile visit logger",
      "Customer history & timeline",
      "Counter QR Code for voluntary signups",
      "Manual WhatsApp 1-click links",
      "Daily revenue & customer counts",
      "CSV data export",
    ],
  },
  {
    id: "growth",
    name: "Growth Plan",
    price_monthly_inr: 799,
    description: "Our most popular plan for established restaurants, salons, and businesses.",
    max_customers: 1500,
    badge: "Most Popular",
    is_popular: true,
    features: [
      "Up to 1,500 active customer records",
      "Daily AI Analysis & trend explanation",
      "Automated customer segmentation (VIP, Inactive, At-Risk)",
      "Smart Action Center & Opportunities feed",
      "Personalized WhatsApp template generator",
      "Campaign return tracking & ROI measurement",
      "Advanced retention curves & repeat rate",
      "Up to 3 staff member accounts",
    ],
  },
  {
    id: "pro",
    name: "Pro Retention Suite",
    price_monthly_inr: 1199,
    description: "For high-volume businesses and multi-staff teams demanding maximum repeat revenue.",
    max_customers: 10000,
    badge: "Maximum ROI",
    features: [
      "Unlimited customer records & visits",
      "Deep retention & cohort analytics",
      "Predictive customer-loss alerts",
      "Unlimited staff & role permissions",
      "Priority WhatsApp message generation & tags",
      "Automated weekly executive PDF summaries",
      "Direct phone & priority support",
    ],
  },
];

export const DEFAULT_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  // --- UNIVERSAL / ALL INDUSTRIES ---
  {
    id: "tpl-thankyou-universal",
    business_id: null,
    industry: null,
    name: "Thank You & Welcome Reward",
    category: "thank_you",
    message:
      "Hi {customer_name}! 🌟 Thank you for visiting {business_name} today. We hope you loved your experience! Show this message on your next visit for a complimentary surprise perk on us. See you soon! 😊",
    is_default: true,
  },
  {
    id: "tpl-comeback-universal",
    business_id: null,
    industry: null,
    name: "Inactive Comeback Offer ({offer_discount}% OFF)",
    category: "comeback",
    message:
      "Hi {customer_name}, we missed you at {business_name}! It's been {days_since_last_visit} days since your last visit. We'd love to welcome you back with a special {offer_discount}% OFF on your bill this week. Just show this message at the counter! 🎁",
    is_default: true,
  },
  {
    id: "tpl-vip-universal",
    business_id: null,
    industry: null,
    name: "VIP Member Exclusive Appreciation",
    category: "vip_offer",
    message:
      "Hello {customer_name}! ✨ You are one of our most valued VIP guests at {business_name}. As a thank you for your loyal support, your next visit includes an exclusive member upgrade. We look forward to hosting you again soon! 🥂",
    is_default: true,
  },
  {
    id: "tpl-reminder-universal",
    business_id: null,
    industry: null,
    name: "Gentle Check-In / Catch-Up",
    category: "reminder",
    message:
      "Hi {customer_name}, how have you been? It's been a little while since you dropped by {business_name}. We have some exciting new specials waiting for you. Come say hi this week! ✨",
    is_default: true,
  },
  {
    id: "tpl-weekend-universal",
    business_id: null,
    industry: null,
    name: "Weekend Special Invitation",
    category: "festival",
    message:
      "Hey {customer_name}! Planning your weekend? Join us at {business_name} for our special weekend highlights and seasonal specials. Reserve your spot or walk in today! 🎉",
    is_default: true,
  },

  // --- RESTAURANT & FINE DINING ---
  {
    id: "tpl-rest-thankyou",
    business_id: null,
    industry: "restaurant",
    name: "Dining Thank You & Chef's Dessert Perk",
    category: "thank_you",
    message:
      "Hi {customer_name}! 🍽️ Thank you for dining with us at {business_name}. We hope you enjoyed your meal! On your next visit, enjoy a complimentary dessert or beverage on the house when you show this message. Bon appétit!",
    is_default: true,
  },
  {
    id: "tpl-rest-comeback",
    business_id: null,
    industry: "restaurant",
    name: "Dinner Table Win-Back ({offer_discount}% OFF)",
    category: "comeback",
    message:
      "Hey {customer_name}, your favorite table at {business_name} misses you! It's been {days_since_last_visit} days since we last hosted you. Come by for lunch or dinner this week and enjoy {offer_discount}% OFF your total food bill! 🍷🍕",
    is_default: true,
  },
  {
    id: "tpl-rest-vip",
    business_id: null,
    industry: "restaurant",
    name: "VIP Chef's Tasting Special",
    category: "vip_offer",
    message:
      "Dear {customer_name}, as one of {business_name}'s premier VIP patrons, our Head Chef would love to curate a complimentary signature appetizer pairing on your next reservation. Reply to book your VIP table! 🍾✨",
    is_default: true,
  },
  {
    id: "tpl-rest-midweek",
    business_id: null,
    industry: "restaurant",
    name: "Midweek 1+1 Course Lunch Offer",
    category: "festival",
    message:
      "Hi {customer_name}! Beat the weekday rush with our Chef's Special Lunch Deal at {business_name}. Order any main course and get 50% OFF your appetizer or beverage. Valid Monday through Thursday! 🥗🍜",
    is_default: true,
  },

  // --- CAFÉ & BAKERY ---
  {
    id: "tpl-cafe-thankyou",
    business_id: null,
    industry: "cafe",
    name: "Coffee Welcome & Free Artisanal Cookie",
    category: "thank_you",
    message:
      "Hey {customer_name}! ☕ Thanks for grabbing your coffee/bites at {business_name} today. Show this message on your next visit for a FREE fresh-baked cookie or pastry with your beverage! See you tomorrow morning!",
    is_default: true,
  },
  {
    id: "tpl-cafe-comeback",
    business_id: null,
    industry: "cafe",
    name: "Missing Your Coffee Ritual ({offer_discount}% OFF)",
    category: "comeback",
    message:
      "Hi {customer_name}, we haven't seen your smiling face at {business_name} for {days_since_last_visit} days! Your favorite brews are waiting. Drop in this week for {offer_discount}% OFF your coffee & bakery order! 🥐☕",
    is_default: true,
  },
  {
    id: "tpl-cafe-vip",
    business_id: null,
    industry: "cafe",
    name: "VIP Free Beverage Size Upgrade",
    category: "vip_offer",
    message:
      "Hey {customer_name}! 🌟 You're an official member of the {business_name} VIP Coffee Club. Enjoy a complimentary size upgrade + choice of artisanal oat/almond milk on us every visit this month!",
    is_default: true,
  },
  {
    id: "tpl-cafe-pastry",
    business_id: null,
    industry: "cafe",
    name: "Fresh Morning Bakery Batch Alert",
    category: "festival",
    message:
      "Good morning {customer_name}! 🥐 Our ovens just finished a warm batch of fresh sourdough croissants and specialty bakes at {business_name}. Swing by for the ultimate breakfast pairing before they sell out! ☀️",
    is_default: true,
  },

  // --- SALON, SPA & BEAUTY ---
  {
    id: "tpl-salon-thankyou",
    business_id: null,
    industry: "salon_spa",
    name: "Post-Service Glow Check-In & Care Tips",
    category: "thank_you",
    message:
      "Hi {customer_name}! 💖 We loved pampering you at {business_name} today! Hope you are loving your new look/glow. Tag us in your selfie or show this text on your next session for a complimentary hair spa/serum treatment! ✨",
    is_default: true,
  },
  {
    id: "tpl-salon-rebook",
    business_id: null,
    industry: "salon_spa",
    name: "3-4 Week Re-Booking & Maintenance Due",
    category: "reminder",
    message:
      "Hello {customer_name}! ✨ It's been {days_since_last_visit} days since your last pampering session at {business_name}. To keep your hair, skin & nails looking flawless, now is the ideal time to re-book. Reply YES to reserve your preferred slot!",
    is_default: true,
  },
  {
    id: "tpl-salon-comeback",
    business_id: null,
    industry: "salon_spa",
    name: "Comeback Pamper Package ({offer_discount}% OFF)",
    category: "comeback",
    message:
      "Dear {customer_name}, time for some well-deserved me-time! We missed you at {business_name}. Book any salon or spa service this week and receive a flat {offer_discount}% OFF plus a free herbal mask. Reply to book! 💆‍♀️💅",
    is_default: true,
  },
  {
    id: "tpl-salon-vip",
    business_id: null,
    industry: "salon_spa",
    name: "VIP Priority Stylist & Free Deep Conditioning",
    category: "vip_offer",
    message:
      "Hi {customer_name}! As one of our top VIP guests at {business_name}, you receive priority master stylist booking and a complimentary Moroccan oil deep conditioning session on your next appointment. See you soon! 🌸",
    is_default: true,
  },

  // --- GYM & FITNESS STUDIO ---
  {
    id: "tpl-gym-thankyou",
    business_id: null,
    industry: "gym",
    name: "Post-Workout Recovery & Goal Check-In",
    category: "thank_you",
    message:
      "Great workout today, {customer_name}! 💪 Consistency is key to crushing your fitness goals. Stay hydrated and remember to stretch! Catch you at {business_name} for your next sweat session!",
    is_default: true,
  },
  {
    id: "tpl-gym-missyou",
    business_id: null,
    industry: "gym",
    name: "We Miss Your Energy! Consistency Check-In",
    category: "reminder",
    message:
      "Hey {customer_name}, we noticed you haven't checked into {business_name} in {days_since_last_visit} days! Don't let your progress slip. Come in today for an energizing workout — your trainers are ready to support you! 🏋️‍♂️🔥",
    is_default: true,
  },
  {
    id: "tpl-gym-comeback",
    business_id: null,
    industry: "gym",
    name: "Membership Re-Activation & Free PT Session",
    category: "comeback",
    message:
      "Hi {customer_name}! Get back into peak shape with {business_name}. Re-activate your training pass this week and get 1 FREE 1-on-1 Personal Training Consultation + custom nutrition plan! Reply to get started! 🎯",
    is_default: true,
  },
  {
    id: "tpl-gym-friend",
    business_id: null,
    industry: "gym",
    name: "VIP Bring-a-Friend Free Workout Pass",
    category: "vip_offer",
    message:
      "Hey {customer_name}! 🏅 You've been crushing your workouts at {business_name}. As a VIP reward, bring a workout buddy for FREE all this week. Share this pass with your gym partner!",
    is_default: true,
  },

  // --- RETAIL BOUTIQUE & FASHION ---
  {
    id: "tpl-retail-thankyou",
    business_id: null,
    industry: "retail",
    name: "Shopping Thank You & Style Feedback",
    category: "thank_you",
    message:
      "Hi {customer_name}! 🛍️ Thank you for shopping at {business_name}. We hope your new purchases bring you joy and confidence! Show this message on your next visit for a complimentary gift voucher on bill value > {currency_symbol}2,000.",
    is_default: true,
  },
  {
    id: "tpl-retail-comeback",
    business_id: null,
    industry: "retail",
    name: "Wardrobe Refresh Voucher ({offer_discount}% OFF)",
    category: "comeback",
    message:
      "Hey {customer_name}, we have fresh new arrivals waiting for you at {business_name}! It's been {days_since_last_visit} days since your last shopping spree. Enjoy a special {offer_discount}% OFF on all new seasonal collections this weekend! 👗✨",
    is_default: true,
  },
  {
    id: "tpl-retail-vip",
    business_id: null,
    industry: "retail",
    name: "VIP Private Preview & Early Collection Access",
    category: "vip_offer",
    message:
      "Exclusive for {customer_name}! ✨ As a VIP Patron of {business_name}, we invite you to an exclusive 24-hour private preview of our upcoming festive collection before public release. Come explore first picks! 🎁",
    is_default: true,
  },
  {
    id: "tpl-retail-birthday",
    business_id: null,
    industry: "retail",
    name: "Birthday Month Special Wardrobe Gift",
    category: "festival",
    message:
      "Happy Birthday Month {customer_name}! 🎂 Celebrate your special day with {business_name}. Enjoy a special gift discount of {offer_discount}% OFF + a complimentary styling session during your birthday week! 🎈",
    is_default: true,
  },

  // --- CLINIC, HEALTH & WELLNESS ---
  {
    id: "tpl-clinic-thankyou",
    business_id: null,
    industry: "clinic",
    name: "Post-Consultation Wellness Check-In",
    category: "thank_you",
    message:
      "Hello {customer_name}, thank you for visiting {business_name}. We hope you are feeling well. Please adhere to your prescribed regimen and reach out if you have any questions or follow-up needs. Wishing you great health! 🩺💚",
    is_default: true,
  },
  {
    id: "tpl-clinic-routine",
    business_id: null,
    industry: "clinic",
    name: "Routine Health / Dental Check-Up Due",
    category: "reminder",
    message:
      "Hi {customer_name}, this is a gentle reminder from {business_name} that your periodic wellness/dental check-up is due. Regular preventive care keeps you healthy and energized. Reply to schedule your preferred time slot! 👨‍⚕️",
    is_default: true,
  },
  {
    id: "tpl-clinic-package",
    business_id: null,
    industry: "clinic",
    name: "Family Preventive Health Screening Offer",
    category: "comeback",
    message:
      "Dear {customer_name}, prioritize your family's health this month at {business_name}. Avail our comprehensive Annual Preventive Health Check-Up package with a special {offer_discount}% discount. Reply for details! 🏥🌿",
    is_default: true,
  },

  // --- CLOTHING SHOP & BOUTIQUE ---
  {
    id: "tpl-clothing-newstock",
    business_id: null,
    industry: "clothing",
    name: "New Stock / Collection Arrival",
    category: "festival",
    message:
      "Hi {customer_name}! 👋 New collection has arrived at {business_name}. Visit us to check out the latest styles and trendy designs. See you soon! 😊",
    is_default: true,
  },
  {
    id: "tpl-clothing-festival",
    business_id: null,
    industry: "clothing",
    name: "Festival Offer & Season Sale ({offer_discount}% OFF)",
    category: "festival",
    message:
      "Hey {customer_name}! 🌟 Celebrate the festive season in style with {business_name}. Enjoy special festive discounts of {offer_discount}% OFF on your favorite outfits this week! 🛍️✨",
    is_default: true,
  },
  {
    id: "tpl-clothing-loyal",
    business_id: null,
    industry: "clothing",
    name: "VIP Loyal Shopper Preview Perk",
    category: "vip_offer",
    message:
      "Dear {customer_name}, as one of our most valued shoppers at {business_name}, enjoy an exclusive VIP preview and special member discount on our new arrivals! 💖👗",
    is_default: true,
  },
  {
    id: "tpl-clothing-inactive",
    business_id: null,
    industry: "clothing",
    name: "Inactive Shopper Comeback ({offer_discount}% OFF)",
    category: "comeback",
    message:
      "Hi {customer_name}, we missed you at {business_name}! It's been {days_since_last_visit} days. Refresh your wardrobe with {offer_discount}% OFF on your next visit! 👗✨",
    is_default: true,
  },

  // --- PG (PAYING GUEST) & HOSTEL ---
  {
    id: "tpl-pg-rent-due",
    business_id: null,
    industry: "pg_hostel",
    name: "Monthly Rent Due Reminder",
    category: "reminder",
    message:
      "Hi {customer_name}, this is a gentle reminder from {business_name} that your PG rent is due soon. Please clear your dues at the earliest. Thank you! 🏠",
    is_default: true,
  },
  {
    id: "tpl-pg-payment-receipt",
    business_id: null,
    industry: "pg_hostel",
    name: "Rent Payment Confirmation & Receipt",
    category: "thank_you",
    message:
      "Hi {customer_name}! Thank you for your rent payment to {business_name}. We have recorded your payment successfully. Have a wonderful and peaceful stay! ✨🏠",
    is_default: true,
  },
  {
    id: "tpl-pg-welcome",
    business_id: null,
    industry: "pg_hostel",
    name: "New Resident Welcome & House Rules",
    category: "thank_you",
    message:
      "Welcome to {business_name}, {customer_name}! 🏠 We are thrilled to have you with us. If you need any assistance with your room or facilities, please reach out anytime!",
    is_default: true,
  },

  // --- HOTEL & HOSPITALITY ---
  {
    id: "tpl-hotel-thankyou",
    business_id: null,
    industry: "hotel",
    name: "Post-Stay Hospitality Thank You & Feedback",
    category: "thank_you",
    message:
      "Dear {customer_name}, thank you for choosing {business_name} for your stay. It was our absolute pleasure hosting you! We hope you had a restful trip. As a returning guest perk, enjoy complimentary breakfast on your next booking! 🏨🌟",
    is_default: true,
  },
  {
    id: "tpl-hotel-comeback",
    business_id: null,
    industry: "hotel",
    name: "Weekend Staycation ({offer_discount}% OFF + Upgrade)",
    category: "comeback",
    message:
      "Hello {customer_name}, ready for another relaxing escape? Book your next staycation at {business_name} this month and enjoy {offer_discount}% OFF room rates + a complimentary room category upgrade! Reply to reserve. 🌴🧳",
    is_default: true,
  },
];

export const SEED_BUSINESSES: Business[] = [
  {
    id: "biz-1",
    name: "Revia Kitchen & Bistro",
    industry: "restaurant",
    owner_name: "Revia Owner",
    owner_email: "revia@revia.com",
    phone: "+91 98201 12345",
    currency: "INR",
    currency_symbol: "₹",
    address: "12, Indiranagar 100ft Road, Bengaluru",
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    trial_start_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    trial_end_date: new Date(Date.now() + 9 * 86400000).toISOString(),
    subscription_status: "trialing",
    subscription_plan: "growth",
    default_comeback_discount: 15,
    whatsapp_signature: "— Vikram & Team, Revia Bistro",
    qr_loyalty_perk: "Get 10% OFF on your next dining visit!",
  },
  {
    id: "biz-2",
    name: "Aura Luxury Spa & Salon",
    industry: "salon_spa",
    owner_name: "Pooja Sharma",
    owner_email: "pooja@auraspa.in",
    phone: "+91 98112 54321",
    currency: "INR",
    currency_symbol: "₹",
    address: "45 Jubilee Hills, Hyderabad",
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    trial_start_date: new Date(Date.now() - 20 * 86400000).toISOString(),
    trial_end_date: new Date(Date.now() - 6 * 86400000).toISOString(),
    subscription_status: "active",
    subscription_plan: "pro",
    default_comeback_discount: 20,
    whatsapp_signature: "— Aura Wellness Team",
    qr_loyalty_perk: "Enjoy a free head massage upgrade on your next service!",
  },
  {
    id: "biz-3",
    name: "Pulse Fitness & Crossfit Studio",
    industry: "gym",
    owner_name: "Arjun Rawat",
    owner_email: "arjun@pulsefit.com",
    phone: "+91 97410 99887",
    currency: "INR",
    currency_symbol: "₹",
    address: "7th Block Koramangala, Bengaluru",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    trial_start_date: new Date(Date.now() - 2 * 86400000).toISOString(),
    trial_end_date: new Date(Date.now() + 12 * 86400000).toISOString(),
    subscription_status: "trialing",
    subscription_plan: "starter",
    default_comeback_discount: 10,
    whatsapp_signature: "— Coach Arjun, Pulse Studio",
    qr_loyalty_perk: "Get 1 complimentary personal training session!",
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "cust-1",
    business_id: "biz-1",
    name: "Rahul Deshmukh",
    phone: "+91 98200 11223",
    is_anonymous: false,
    segment: "vip",
    total_visits: 14,
    total_spend: 18450,
    avg_bill: 1318,
    avg_visit_interval_days: 4,
    first_visit_date: new Date(Date.now() - 55 * 86400000).toISOString(),
    last_visit_date: new Date(Date.now() - 2 * 86400000).toISOString(),
    favorite_items: ["Truffle Pasta", "Cold Brew", "Grilled Salmon"],
    notes: "Loves table 4 by the window. Celebrated anniversary here.",
    tags: ["Foodie", "Weekend Regular", "High Spender"],
    opt_in_source: "staff_entry",
    created_at: new Date(Date.now() - 55 * 86400000).toISOString(),
  },
  {
    id: "cust-2",
    business_id: "biz-1",
    name: "Ananya Iyer",
    phone: "+91 98450 33445",
    is_anonymous: false,
    segment: "becoming_inactive",
    total_visits: 8,
    total_spend: 9600,
    avg_bill: 1200,
    avg_visit_interval_days: 6,
    first_visit_date: new Date(Date.now() - 60 * 86400000).toISOString(),
    last_visit_date: new Date(Date.now() - 17 * 86400000).toISOString(),
    favorite_items: ["Avocado Sourdough", "Berry Smoothie"],
    notes: "Usually visits for Sunday brunch with family.",
    tags: ["Brunch Regular", "At Risk"],
    opt_in_source: "counter_qr",
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: "cust-3",
    business_id: "biz-1",
    name: "Karthik Sundaram",
    phone: "+91 99001 55667",
    is_anonymous: false,
    segment: "inactive",
    total_visits: 6,
    total_spend: 7800,
    avg_bill: 1300,
    avg_visit_interval_days: 7,
    first_visit_date: new Date(Date.now() - 90 * 86400000).toISOString(),
    last_visit_date: new Date(Date.now() - 38 * 86400000).toISOString(),
    favorite_items: ["Woodfired Pizza", "Tiramisu"],
    notes: "Used to come after office on Thursdays.",
    tags: ["Win Back Candidate"],
    opt_in_source: "staff_entry",
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: "cust-4",
    business_id: "biz-1",
    name: "Sneha Kapur",
    phone: "+91 98190 77889",
    is_anonymous: false,
    segment: "regular",
    total_visits: 5,
    total_spend: 5400,
    avg_bill: 1080,
    avg_visit_interval_days: 8,
    first_visit_date: new Date(Date.now() - 40 * 86400000).toISOString(),
    last_visit_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    favorite_items: ["Cappuccino", "Signature Cheesecake"],
    tags: ["Coffee Lover", "Remote Worker"],
    opt_in_source: "counter_qr",
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: "cust-5",
    business_id: "biz-1",
    name: "Devendra Patel",
    phone: "+91 97123 44556",
    is_anonymous: false,
    segment: "new",
    total_visits: 1,
    total_spend: 1450,
    avg_bill: 1450,
    avg_visit_interval_days: 0,
    first_visit_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    last_visit_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    favorite_items: ["Paneer Tikka Platter", "Garlic Naan"],
    notes: "First time guest, came with colleagues.",
    tags: ["New Customer", "First Timer"],
    opt_in_source: "counter_qr",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "cust-6",
    business_id: "biz-1",
    name: "Meera Sen",
    phone: "+91 98311 99001",
    is_anonymous: false,
    segment: "becoming_inactive",
    total_visits: 4,
    total_spend: 4900,
    avg_bill: 1225,
    avg_visit_interval_days: 5,
    first_visit_date: new Date(Date.now() - 35 * 86400000).toISOString(),
    last_visit_date: new Date(Date.now() - 15 * 86400000).toISOString(),
    favorite_items: ["Greek Salad", "Iced Matcha Latte"],
    tags: ["Health Conscious"],
    opt_in_source: "staff_entry",
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: "cust-7",
    business_id: "biz-1",
    name: "Rohan Varma",
    phone: "+91 99200 88776",
    is_anonymous: false,
    segment: "regular",
    total_visits: 7,
    total_spend: 8100,
    avg_bill: 1157,
    avg_visit_interval_days: 6,
    first_visit_date: new Date(Date.now() - 48 * 86400000).toISOString(),
    last_visit_date: new Date(Date.now() - 1 * 86400000).toISOString(),
    favorite_items: ["Burgers", "Craft Lemonade"],
    tags: ["Regular"],
    opt_in_source: "staff_entry",
    created_at: new Date(Date.now() - 48 * 86400000).toISOString(),
  },
];

export const SEED_VISITS: Visit[] = [
  {
    id: "vis-101",
    business_id: "biz-1",
    customer_id: "cust-1",
    customer_name: "Rahul Deshmukh",
    customer_phone: "+91 98200 11223",
    amount: 1450,
    is_anonymous: false,
    notes: "Dinner with colleague. Ordered pasta & mocktails.",
    items: ["Truffle Pasta", "Mocktail"],
    date: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "vis-102",
    business_id: "biz-1",
    amount: 820,
    is_anonymous: true,
    notes: "Table 2 - Quick lunch coffee & sandwich",
    items: ["Cappuccino", "Club Sandwich"],
    date: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "vis-103",
    business_id: "biz-1",
    customer_id: "cust-7",
    customer_name: "Rohan Varma",
    customer_phone: "+91 99200 88776",
    amount: 1250,
    is_anonymous: false,
    notes: "Evening burger & fries combo",
    items: ["Gourmet Burger", "Loaded Fries"],
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "vis-104",
    business_id: "biz-1",
    customer_id: "cust-4",
    customer_name: "Sneha Kapur",
    customer_phone: "+91 98190 77889",
    amount: 680,
    is_anonymous: false,
    notes: "Work session with latte and cheesecake",
    items: ["Cappuccino", "Cheesecake"],
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "vis-105",
    business_id: "biz-1",
    customer_id: "cust-5",
    customer_name: "Devendra Patel",
    customer_phone: "+91 97123 44556",
    amount: 1450,
    is_anonymous: false,
    notes: "First time visit via table QR code signup",
    items: ["Paneer Tikka", "Garlic Naan"],
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "vis-106",
    business_id: "biz-1",
    amount: 1100,
    is_anonymous: true,
    notes: "Counter takeaway order",
    items: ["Takeaway Box", "Beverages"],
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "vis-107",
    business_id: "biz-1",
    customer_id: "cust-2",
    customer_name: "Ananya Iyer",
    customer_phone: "+91 98450 33445",
    amount: 1350,
    is_anonymous: false,
    notes: "Sunday brunch visit",
    items: ["Avocado Sourdough", "Berry Smoothie"],
    date: new Date(Date.now() - 17 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 17 * 86400000).toISOString(),
  },
  {
    id: "vis-108",
    business_id: "biz-1",
    customer_id: "cust-3",
    customer_name: "Karthik Sundaram",
    customer_phone: "+91 99001 55667",
    amount: 1550,
    is_anonymous: false,
    notes: "Thursday evening pizza",
    items: ["Woodfired Pizza", "Tiramisu"],
    date: new Date(Date.now() - 38 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 38 * 86400000).toISOString(),
  },
];

export const SEED_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-1",
    business_id: "biz-1",
    customer_id: "cust-2",
    customer_name: "Ananya Iyer",
    customer_phone: "+91 98450 33445",
    type: "at_risk",
    priority: "high",
    reason: "Usually visits every 6 days. Last seen 17 days ago (11 days overdue).",
    days_since_last_visit: 17,
    expected_interval: 6,
    potential_revenue: 1200,
    recommended_action: "Send Weekend Brunch 15% Comeback Offer on WhatsApp.",
    status: "pending",
    created_at: new Date().toISOString(),
  },
  {
    id: "opp-2",
    business_id: "biz-1",
    customer_id: "cust-3",
    customer_name: "Karthik Sundaram",
    customer_phone: "+91 99001 55667",
    type: "inactive_winback",
    priority: "high",
    reason: "Inactive for 38 days (previously visited 6 times with avg bill ₹1,300).",
    days_since_last_visit: 38,
    expected_interval: 7,
    potential_revenue: 1300,
    recommended_action: "Send 'We Miss You' 20% Win-Back discount.",
    status: "pending",
    created_at: new Date().toISOString(),
  },
  {
    id: "opp-3",
    business_id: "biz-1",
    customer_id: "cust-6",
    customer_name: "Meera Sen",
    customer_phone: "+91 98311 99001",
    type: "at_risk",
    priority: "medium",
    reason: "Usually visits every 5 days. Last visited 15 days ago.",
    days_since_last_visit: 15,
    expected_interval: 5,
    potential_revenue: 1225,
    recommended_action: "Send Healthy Specials check-in message.",
    status: "pending",
    created_at: new Date().toISOString(),
  },
  {
    id: "opp-4",
    business_id: "biz-1",
    customer_id: "cust-5",
    customer_name: "Devendra Patel",
    customer_phone: "+91 97123 44556",
    type: "new_customer_retention",
    priority: "medium",
    reason: "First-time visitor 3 days ago. Prime window to convert into a repeat customer.",
    days_since_last_visit: 3,
    expected_interval: 7,
    potential_revenue: 1450,
    recommended_action: "Send 2nd visit welcome perk / thank-you voucher.",
    status: "pending",
    created_at: new Date().toISOString(),
  },
];

export const SEED_WHATSAPP_LOGS: WhatsAppLog[] = [
  {
    id: "log-1",
    business_id: "biz-1",
    customer_id: "cust-1",
    customer_name: "Rahul Deshmukh",
    customer_phone: "+91 98200 11223",
    template_name: "VIP Member Exclusive Perk",
    message_sent:
      "Hello Rahul Deshmukh! ✨ You are one of our most valued VIP guests at Revia Bistro. As a thank you for your loyalty, your next visit includes an exclusive chef upgrade. We look forward to hosting you again! 🥂",
    status: "returned",
    sent_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    return_recorded_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    return_revenue: 1450,
  },
  {
    id: "log-2",
    business_id: "biz-1",
    customer_id: "cust-4",
    customer_name: "Sneha Kapur",
    customer_phone: "+91 98190 77889",
    template_name: "Thank You & Welcome",
    message_sent:
      "Hi Sneha Kapur! 🌟 Thank you for visiting Revia Bistro today. We hope you loved your coffee! Show this message on your next visit for a complimentary treat on us.",
    status: "returned",
    sent_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    return_recorded_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    return_revenue: 680,
  },
];
